Capa.Presentacion/Controllers/EmpleadoController.cs
using Capa.Negocio;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using System.Collections.Generic;
using Capa.Entidades;
using Capa.Entidades.ViewModel;
using Newtonsoft.Json;

namespace Capa.Presentacion.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly IMapper mapper;
        private CnEmpleado cnEmpleado = new CnEmpleado();

        public EmpleadoController(IMapper mapper)
        {
            this.mapper = mapper;
        }

        public IActionResult EmpleadoIndex()
        {
            return View();
        }

        public async Task<JsonResult> ObtenerEmplados()
        {
            var TodosEmpleadosDatos = await cnEmpleado.GetEmpleados();

            var todosEmpleadoMostrar = mapper.Map<List<EmpleadoViewModel>>(TodosEmpleadosDatos);
             
            return Json(new { data = todosEmpleadoMostrar }, new JsonSerializerSettings());
        }

        [HttpPost]
        public async Task<JsonResult> GuadarEmpleado([FromBody] EmpleadoViewModel empleadoModel)
        {
            object resultado=false;

            var empleado = mapper.Map<Empleado>(empleadoModel);

            if (!ModelState.IsValid)
            {
                return Json(new { resultado = resultado }, new JsonSerializerSettings());
            }

            if(empleado != null)
            {
                if (empleado.Idempleado == 0)
                {
                    resultado = await cnEmpleado.AgregarEmpleado(empleado);
                }
                else
                {
                    resultado = await cnEmpleado.EditarEmpleado(empleado);
                }
            }

            return Json(new { resultado = resultado }, new JsonSerializerSettings());
        }

        [HttpGet]
        public async Task<JsonResult> EliminarEmpleado(int Id)
        {
            bool resultado= await cnEmpleado.EliminarEmpleado(Id);

            return Json(new { resultado = resultado }, new JsonSerializerSettings());
        }
    }
}

Capa.Presentacion/Controllers/ProductoController.cs
using Capa.Negocio;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using System.Collections.Generic;
using Capa.Entidades;
using Capa.Entidades.ViewModel;
using Newtonsoft.Json;
using System.Linq;

namespace Capa.Presentacion.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IMapper mapper;
        private CnProducto objProducto = new CnProducto();

        public ProductoController(IMapper mapper)
        {
            this.mapper = mapper;
        }

        public IActionResult ProductoIndex()
        {
            return View();
        }

        public async Task<JsonResult> ObtenerProducto()
        {
            var TodosProductoDatos = await objProducto.GetProductos();

            var todosProductoMostrar = (from d in TodosProductoDatos
                                        select new ProductoViewModel
                                        {
                                            Idproducto = d.Idproducto,
                                            Nombre = d.Nombre,
                                            Precio = d.Precio,
                                            Total = d.Cantidad * d.Precio,
                                            Provedor = d.Provedor,
                                            Cantidad = d.Cantidad,
                                            ProvedorNavigation = new ProveedorViewModel()
                                            {
                                                Nombre = d.ProvedorNavigation.Nombre,
                                                Tipo = d.ProvedorNavigation.Tipo
                                            }
                                        }).ToList();
            

            return Json(new { data = todosProductoMostrar }, new JsonSerializerSettings());
        }

        [HttpPost]
        public async Task<JsonResult> GuadarProducto([FromBody] ProductoViewModel productoModel)
        {
            object resultado = false;

            var producto = mapper.Map<Producto>(productoModel);

            if (!ModelState.IsValid)
            {
                return Json(new { resultado = resultado }, new JsonSerializerSettings());
            }

            if (producto != null)
            {
                if (producto.Idproducto == 0)
                {
                    resultado = await objProducto.AgregarProducto(producto);
                }
                else
                {
                    resultado = await objProducto.EditarProducto(producto);
                }
            }

            return Json(new { resultado = resultado }, new JsonSerializerSettings());
        }

        [HttpGet]
        public async Task<JsonResult> EliminarProducto(int Id)
        {
            bool resultado = await objProducto.EliminarProducto(Id);

            return Json(new { resultado = resultado }, new JsonSerializerSettings());
        }
    }
}

Capa.Presentacion/Controllers/ProveedorController.cs
using Capa.Negocio;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using System.Collections.Generic;
using Capa.Entidades;
using Capa.Entidades.ViewModel;
using Newtonsoft.Json;

namespace Capa.Presentacion.Controllers
{
    public class ProveedorController : Controller
    {
        private readonly IMapper mapper;
        private CnProveedor cnProveedor = new CnProveedor();

        public ProveedorController(IMapper mapper)
        {
            this.mapper = mapper;
        }

        public IActionResult ProveedorIndex()
        {
            return View();
        }

        public async Task<JsonResult> ObtenerProveedores()
        {
            var TodosProveedorDatos = await cnProveedor.GetProveedores();

            var todosProveedorMostrar = mapper.Map<List<ProveedorViewModel>>(TodosProveedorDatos);

            return Json(new { data = todosProveedorMostrar }, new JsonSerializerSettings());
        }

        [HttpPost]
        public JsonResult GuadarProveedor([FromBody] ProveedorViewModel provedorModel)
        {
            object resultado = false;
            string mensaje = string.Empty;

            var proveedor = mapper.Map<Provedor>(provedorModel);

            if (!ModelState.IsValid)
            {
                return Json(new { resultado = resultado }, new JsonSerializerSettings());
            }

            if (proveedor != null)
            {
                if (proveedor.Idprovedor == 0)
                {
                    resultado = cnProveedor.AgregarProveedor(proveedor, out mensaje);
                }
                else
                {
                    resultado = cnProveedor.EditarProveedor(proveedor, out mensaje);
                }
            }

            return Json(new { resultado = resultado, mensaje = mensaje }, new JsonSerializerSettings());
        }

        [HttpGet]
        public JsonResult EliminarProveedor(int Id)
        {
            string mensaje = string.Empty;

            bool resultado = cnProveedor.EliminarProveedor(Id, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, new JsonSerializerSettings());
        }
    }
}

Capa.Presentacion/Views/Empleado/EmpleadoIndex.cshtml
<div class="card">
    <div class="card-header">
        <h6 class="card-title">Empleados</h6>
    </div>
    <div class="card-body">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" style="margin: 10px;" onclick="abrirModal(null)">
            Crear Nuevo
        </button>

        <table id="tabla" class="table w-100">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Sexo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white">Usuario</h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtId" type="hidden" value="0" />

                <div class="row g-2">
                    <div class="col-sm-6">
                        <label for="txtNombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="txtNombre" autocomplete="off">
                        <span asp-validation-for="Nombre"></span>
                    </div>

                    <div class="col-sm-6">
                        <label for="txtApellido" class="form-label">Apellido</label>
                        <input type="text" class="form-control" id="txtApellido" autocomplete="off">
                        <span asp-validation-for="Apellido"></span>
                    </div>
                    <div class="col-sm-6">
                        <label for="cboSexo" class="form-label">Genero</label>
                        <select id="cboSexo" class="form-select">
                            <option value="0" disabled>Seleccione</option>
                            <option value="m">Masculino</option>
                            <option value="f">Femenino</option>
                        </select>
                        <span asp-validation-for="Sexo"></span>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">

                        </div>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var dataTabla;
        var filaSeleccionada;

        dataTabla = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                 url: "@Url.Action("ObtenerEmplados", "Empleado")",
                 type: "GET",
                dataType: "json",
                contentType: "application/json"
            },
            "columns":
                [
                    { "data": "Nombre"},
                    { "data": "Apellido"},
                    { "data": "Sexo" },
                    {
                        "defaultContent": "<button type='button' class='btn btn-primary btn-sm btn-editar'><i class='fa fa-pen'></i></button>" +
                            "<button type='button' class='btn btn-danger btn-sm ms-2 btn-eliminar'><i class='fa fa-trash'></i><</button>",
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"
                    }
                ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }
        });
        function abrirModal(json) {
           $("#txtId").val(0);
            $("#txtNombre").val("");
            $("#txtApellido").val("");
            $("#cboSexo").val("");

            if (json != null) {
                $("#txtId").val(json.Idempleado);
                $("#txtNombre").val(json.Nombre);
                $("#txtApellido").val(json.Apellido);
                $("#cboSexo").val(json.Sexo);
            }
            $("#formModal").modal("show")
            $("#mensajeError").hide()
        }
        $("#tabla tbody").on("click", ".btn-editar", function () {
            filaSeleccionada = $(this).closest("tr");
            var datos = dataTabla.row(filaSeleccionada).data();
            abrirModal(datos);
        });

        $("#tabla tbody").on("click", ".btn-eliminar", function () {
            filaSeleccionada = $(this).closest("tr");
            var datos = dataTabla.row(filaSeleccionada).data();
            let urlEliminar = '@Url.Content("~/Empleado/EliminarEmpleado?Id=")' + datos.Idempleado;
            var confirmar = confirm("Esta seguro que desea eliminar este registro")

            if (confirmar) {
                //document.location.href = '@Url.Content("~/Empleado/EliminarEmpleado?Id=")' + datos.Idempleado;

                jQuery.ajax({
                    url: urlEliminar,
                    data: {
                        Id: datos.Idempleado
                    },
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json",
                    success: function (data) {
                        if (data.resultado) {
                            alert("Eliminado con exito");
                            dataTabla.row(filaSeleccionada).remove().draw(false)
                        }
                    },
                    error: function (error) {
                        console.log(error);
                    }
                })

            }
        });

        function Guardar() {

            var empleado = {
                    Idempleado: $("#txtId").val(),
                    Nombre: $("#txtNombre").val(),
                    Apellido: $("#txtApellido").val(),
                    Sexo: $("#cboSexo").val()
            };


            jQuery.ajax({
                url: "@Url.Action("GuadarEmpleado", "Empleado")",
                type: "POST",
                data: JSON.stringify( empleado) ,
                dataType: "json",
                contentType: "application/json; charset= utf-8 ",
                success: function (data) {

                    let resultado = data.resultado;

                    console.log(data.resultado)
                  $(".modal-body").LoadingOverlay("hide");
                    //empleado nuevo
                    if (empleado.Idempleado == 0) {
                        if (resultado != 0) {
                            empleado.Idempleado = resultado;
                            dataTabla.row.add(empleado).draw(false);
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text();
                            $("#mensajeError").show();
                        }
                    }
                    //empleado editar
                    else {
                        if (resultado) {
                            dataTabla.row(filaSeleccionada).data(empleado).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {

                    console.log(error)
                  $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                  $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                },
            });
        }
    </script>
}

Capa.Presentacion/Views/Producto/ProductoIndex.cshtml
<div class="card">
    <div class="card-header">
        <h6 class="card-title">Productos</h6>
    </div>
    <div class="card-body">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" style="margin: 10px;" onclick="abrirModal(null)">
            Crear Nuevo
        </button>

        <table id="tabla" class="table w-100">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white">Usuario</h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtId" type="hidden" value="0" />

                <div class="row g-2">
                    <div class="col-sm-6">
                        <label for="txtNombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="txtNombre" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="txtPrecio" class="form-label">Precio</label>
                        <input type="number" step="0.01" class="form-control" id="txtPrecio" autocomplete="off">
                    </div>
                    
                    <div class="col-sm-6">
                        <label for="txtCantidad" class="form-label">Cantidad</label>
                        <input type="number" class="form-control" id="txtCantidad" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboProveedor" class="form-label">Proveedor</label>
                        <select id="cboProveedor" class="form-select">

                        </select>
                    </div>
                </div>               

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var dataTabla;
        var filaSeleccionada;

        dataTabla = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                 url: "@Url.Action("ObtenerProducto", "Producto")",
                 type: "GET",
                dataType: "json",
                contentType: "application/json"
            },
            "columns":
                [
                    { "data": "Nombre"},
                    { "data": "Precio" },
                    { "data": "Cantidad" },
                    { "data": "Total" },
                    {
                        "defaultContent": "<button type='button' class='btn btn-primary btn-sm btn-editar'><i class='fa fa-pen'></i></button>" +
                            "<button type='button' class='btn btn-danger btn-sm ms-2 btn-eliminar'><i class='fa fa-trash'></i></button>",
                        "orderable": false,
                        "searchable": false,
                        "width": "90px"
                    }
                ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }
        });


        jQuery.ajax({
            url: "@Url.Action("ObtenerProveedores", "Proveedor")",
            type: "GET",
            dataType: "json",
            contentType: "application/json",
            success: function (data) {
                $("<option>").attr({ "value": "0", "disabled": "true" }).text("Seleccione").appendTo("#cboProveedor");
                $.each(data.data, function (index, valor) {
                    $("<option>").attr({ "value": valor.Idprovedor }).text(valor.Nombre).appendTo("#cboProveedor");
                })
            },
            error: function (error) {
                console.log(error);
            }
        });


        function abrirModal(json) {
           $("#txtId").val(0);
            $("#txtNombre").val("");
            $("#txtPrecio").val("");
            $("#txtCantidad").val("");
            $("#cboProveedor").val("");

            if (json != null) {
                $("#txtId").val(json.Idproducto);
                $("#txtNombre").val(json.Nombre);
                $("#txtPrecio").val(json.Precio);
                $("#txtCantidad").val(json.Cantidad);
                $("#cboProveedor").val(json.Provedor);
            }

            $("#formModal").modal("show");
        }

        $("#tabla tbody").on("click", ".btn-editar", function () {
            filaSeleccionada = $(this).closest("tr");
            var datos = dataTabla.row(filaSeleccionada).data();
            abrirModal(datos);
        });

        $("#tabla tbody").on("click", ".btn-eliminar", function () {
            filaSeleccionada = $(this).closest("tr");
            var datos = dataTabla.row(filaSeleccionada).data();
            let urlEliminar = '@Url.Content("~/Producto/EliminarProducto?Id=")' + datos.Idempleado;
            var confirmar = confirm("Esta seguro que desea eliminar este registro")

            if (confirmar) {
                //document.location.href = '@Url.Content("~/Producto/EliminarProducto?Id=")' + datos.Idempleado;

                jQuery.ajax({
                    url: urlEliminar,
                    data: {
                        Id: datos.Idproducto
                    },
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json",
                    success: function (data) {
                        if (data.resultado) {
                            alert("Eliminado con exito");
                            dataTabla.row(filaSeleccionada).remove().draw(false)
                        }
                    },
                    error: function (error) {
                        console.log(error);
                    }
                })

            }
        });

          function Guardar() {

              var producto = {
                  Idproducto: $("#txtId").val(),
                  Nombre: $("#txtNombre").val(),
                  Precio: $("#txtPrecio").val(),
                  Provedor: $("#cboProveedor option:selected").val(),
                  Cantidad: $("#txtCantidad").val(),
                  Total: $("#txtCantidad").val() * $("#txtPrecio").val()
              };

              console.log(producto.Provedor)

            jQuery.ajax({
                url: "@Url.Action("GuadarProducto", "Producto")",
                type: "POST",
                data: JSON.stringify(producto),
                dataType: "json",
                contentType: "application/json; charset= utf-8 ",
                success: function (data) {

                    let resultado = data.resultado;

                    console.log(resultado)
                  $(".modal-body").LoadingOverlay("hide");
                    //empleado nuevo
                    if (producto.Idproducto == 0) {
                        if (resultado != 0) {
                            producto.Idproducto = resultado;
                            dataTabla.row.add(producto).draw(false);
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text();
                            $("#mensajeError").show();
                        }
                    }
                    //empleado editar
                    else {
                        if (resultado) {
                            dataTabla.row(filaSeleccionada).data(producto).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {

                    console.log(error)
                  $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                  $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                },
            });
        }
    </script>
}

Capa.Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-do">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert/sweetalert.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("EmpleadoIndex","Empleado")">Sistema Inventario</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" style="float: right; text-align: end; justify-content: end;" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("EmpleadoIndex","Empleado")">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("ProveedorIndex","Proveedor")">Proveedor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("ProductoIndex","Producto")">Producto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Capa.Presentacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>